### ISSUE TITLE
Cannot install on an Azure AKS cluster with active directory authentication enabled

### ISSUE THREAD

**Issue by EDeijl** [banzaicloud/backyards-cli#108]
**Describe the bug**
When trying to run `url https://getbackyards.sh | sh && backyards install -a --run-demo` I get the following error:
```

panic: No Auth Provider found for name "azure"

goroutine 1 [running]:
k8s.io/client-go/discovery.NewDiscoveryClientForConfigOrDie(...)
        /go/pkg/mod/k8s.io/client-go@v11.0.1-0.20190516230509-ae8359b20417+incompatible/discovery/discovery_client.go:490
sigs.k8s.io/controller-runtime/pkg/client/apiutil.NewDiscoveryRESTMapper(0xc00000a1e0, 0x0, 0x0, 0x0, 0xc0005db818)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0-beta.4/pkg/client/apiutil/apimachinery.go:38 +0xd9
sigs.k8s.io/controller-runtime/pkg/client.New(0xc00000a1e0, 0xc0002acd90, 0x0, 0x0, 0x0, 0xffffffffffffffff, 0x0, 0x8)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0-beta.4/pkg/client/client.go:66 +0x44c
github.com/banzaicloud/backyards-cli/pkg/k8s/client.NewClient(0xc00000a1e0, 0x0, 0x0, 0x0, 0x203000, 0x7f870e71cb88, 0x1, 0x0)
        /home/circleci/project/pkg/k8s/client/client.go:51 +0x56
github.com/banzaicloud/backyards-cli/pkg/cli.(*backyardsCLI).GetK8sClient(0xc00014c840, 0x80, 0x80, 0x17f5380, 0x1)
        /home/circleci/project/pkg/cli/cli.go:255 +0x61
github.com/banzaicloud/backyards-cli/internal/cli/cmd/istio.(*installCommand).applyResources(0xc0001c9b30, 0xc0001b0040, 0x3, 0x4, 0xc0004a2300, 0xb, 0x10, 0x10, 0x187e460)
        /home/circleci/project/internal/cli/cmd/istio/install.go:162 +0x48
github.com/banzaicloud/backyards-cli/internal/cli/cmd/istio.(*installCommand).run(0xc0001c9b30, 0x1bc9ac0, 0xc00014c840, 0xc00045a930, 0xc0004cc000, 0xc0001c9b30)
        /home/circleci/project/internal/cli/cmd/istio/install.go:132 +0x909
github.com/banzaicloud/backyards-cli/internal/cli/cmd/istio.NewInstallCommand.func1(0xc0004cc000, 0x0, 0x0, 0x0, 0x5d67a7, 0xc000026200)
        /home/circleci/project/internal/cli/cmd/istio/install.go:96 +0x53
github.com/banzaicloud/backyards-cli/internal/cli/cmd.(*installCommand).runSubcommands(0xc00014e300, 0xc0000e4000, 0x0, 0x0)
        /home/circleci/project/internal/cli/cmd/install.go:488 +0x305
github.com/banzaicloud/backyards-cli/internal/cli/cmd.NewInstallCommand.func1(0xc00018c280, 0xc00014eb40, 0x0, 0x2, 0x0, 0x0)
        /home/circleci/project/internal/cli/cmd/install.go:126 +0x7a
github.com/spf13/cobra.(*Command).execute(0xc00018c280, 0xc00014eb00, 0x2, 0x2, 0xc00018c280, 0xc00014eb00)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0x27e0b00, 0x4e02e4, 0xc0002a8820, 0xc00004e050)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/banzaicloud/backyards-cli/pkg/cli/cmd.Execute()
        /home/circleci/project/pkg/cli/cmd/root.go:99 +0x3f
main.main()
        /home/circleci/project/cmd/backyards/main.go:34 +0x8a

```

**Steps to reproduce the issue:**
Run `curl https://getbackyards.sh | sh && backyards install -a --run-demo` against an AKS cluster which has active directory authentication enabled.

**Expected behavior**
I expect it to install backyards

**Additional context**
The fix is probably in the same ballpark as this issue https://github.com/operator-framework/operator-sdk/pull/1199, but I'm not enough of a go expert to really comment on that.

**Comment by waynz0r** [comment]
@EDeijl, thanks for reporting this issue, we just released a new version (1.1.1) with the fix.

Please let us know how it works for you!
